// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UrlMap struct {
	ShortCode string
	Url       string
	CreatedAt pgtype.Timestamptz
}
