// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const createURLMap = `-- name: CreateURLMap :exec
INSERT INTO url_map (short_code, url)
VALUES ($1, $2)
`

type CreateURLMapParams struct {
	ShortCode string
	Url       string
}

func (q *Queries) CreateURLMap(ctx context.Context, arg CreateURLMapParams) error {
	_, err := q.db.Exec(ctx, createURLMap, arg.ShortCode, arg.Url)
	return err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT short_code, url, created_at
FROM url_map
WHERE short_code = $1
LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (UrlMap, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i UrlMap
	err := row.Scan(&i.ShortCode, &i.Url, &i.CreatedAt)
	return i, err
}
