// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: analysis.proto

package server

import (
	"context"

	"url-shortner/services/analytics-rpc/analytics"
	"url-shortner/services/analytics-rpc/internal/logic"
	"url-shortner/services/analytics-rpc/internal/svc"
)

type AnalysisServiceServer struct {
	svcCtx *svc.ServiceContext
	analytics.UnimplementedAnalysisServiceServer
}

func NewAnalysisServiceServer(svcCtx *svc.ServiceContext) *AnalysisServiceServer {
	return &AnalysisServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AnalysisServiceServer) GetAnalytics(ctx context.Context, in *analytics.AnalyticsRequest) (*analytics.AnalyticsResponse, error) {
	l := logic.NewGetAnalyticsLogic(ctx, s.svcCtx)
	return l.GetAnalytics(in)
}

func (s *AnalysisServiceServer) CreateAnalytics(ctx context.Context, in *analytics.AnalyticsRequest) (*analytics.AnalyticsResponse, error) {
	l := logic.NewCreateAnalyticsLogic(ctx, s.svcCtx)
	return l.CreateAnalytics(in)
}

func (s *AnalysisServiceServer) UpdateAnalytics(ctx context.Context, in *analytics.AnalyticsRequest) (*analytics.AnalyticsResponse, error) {
	l := logic.NewUpdateAnalyticsLogic(ctx, s.svcCtx)
	return l.UpdateAnalytics(in)
}

func (s *AnalysisServiceServer) DeleteAnalytics(ctx context.Context, in *analytics.AnalyticsRequest) (*analytics.AnalyticsResponse, error) {
	l := logic.NewDeleteAnalyticsLogic(ctx, s.svcCtx)
	return l.DeleteAnalytics(in)
}
