// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"url-shortner/services/shortner-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:short_url",
				Handler: RedirectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/shorten",
				Handler: ShortenHandler(serverCtx),
			},
		},
	)
}
