// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type RedirectRequest struct {
	ShortURL string `json:"short_url"`
}

type RedirectResponse struct {
	URL string `json:"url"`
}

type ShortenRequest struct {
	URL string `json:"url"`
}

type ShortenResponse struct {
	ShortURL string `json:"short_url"`
}
