// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/analytics-rpc/analysis.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_services_analytics_rpc_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_rpc_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_services_analytics_rpc_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AnalyticsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AnalyticsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type AnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clicks        int32                  `protobuf:"varint,1,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_services_analytics_rpc_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_analytics_rpc_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_services_analytics_rpc_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticsResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *AnalyticsResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_services_analytics_rpc_analysis_proto protoreflect.FileDescriptor

const file_services_analytics_rpc_analysis_proto_rawDesc = "" +
	"\n" +
	"%services/analytics-rpc/analysis.proto\x12\tanalytics\"P\n" +
	"\x10AnalyticsRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"=\n" +
	"\x11AnalyticsResponse\x12\x16\n" +
	"\x06clicks\x18\x01 \x01(\x05R\x06clicks\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url2\xc6\x02\n" +
	"\x0fAnalysisService\x12I\n" +
	"\fGetAnalytics\x12\x1b.analytics.AnalyticsRequest\x1a\x1c.analytics.AnalyticsResponse\x12L\n" +
	"\x0fCreateAnalytics\x12\x1b.analytics.AnalyticsRequest\x1a\x1c.analytics.AnalyticsResponse\x12L\n" +
	"\x0fUpdateAnalytics\x12\x1b.analytics.AnalyticsRequest\x1a\x1c.analytics.AnalyticsResponse\x12L\n" +
	"\x0fDeleteAnalytics\x12\x1b.analytics.AnalyticsRequest\x1a\x1c.analytics.AnalyticsResponseB\rZ\v./analyticsb\x06proto3"

var (
	file_services_analytics_rpc_analysis_proto_rawDescOnce sync.Once
	file_services_analytics_rpc_analysis_proto_rawDescData []byte
)

func file_services_analytics_rpc_analysis_proto_rawDescGZIP() []byte {
	file_services_analytics_rpc_analysis_proto_rawDescOnce.Do(func() {
		file_services_analytics_rpc_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_analytics_rpc_analysis_proto_rawDesc), len(file_services_analytics_rpc_analysis_proto_rawDesc)))
	})
	return file_services_analytics_rpc_analysis_proto_rawDescData
}

var file_services_analytics_rpc_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_analytics_rpc_analysis_proto_goTypes = []any{
	(*AnalyticsRequest)(nil),  // 0: analytics.AnalyticsRequest
	(*AnalyticsResponse)(nil), // 1: analytics.AnalyticsResponse
}
var file_services_analytics_rpc_analysis_proto_depIdxs = []int32{
	0, // 0: analytics.AnalysisService.GetAnalytics:input_type -> analytics.AnalyticsRequest
	0, // 1: analytics.AnalysisService.CreateAnalytics:input_type -> analytics.AnalyticsRequest
	0, // 2: analytics.AnalysisService.UpdateAnalytics:input_type -> analytics.AnalyticsRequest
	0, // 3: analytics.AnalysisService.DeleteAnalytics:input_type -> analytics.AnalyticsRequest
	1, // 4: analytics.AnalysisService.GetAnalytics:output_type -> analytics.AnalyticsResponse
	1, // 5: analytics.AnalysisService.CreateAnalytics:output_type -> analytics.AnalyticsResponse
	1, // 6: analytics.AnalysisService.UpdateAnalytics:output_type -> analytics.AnalyticsResponse
	1, // 7: analytics.AnalysisService.DeleteAnalytics:output_type -> analytics.AnalyticsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_analytics_rpc_analysis_proto_init() }
func file_services_analytics_rpc_analysis_proto_init() {
	if File_services_analytics_rpc_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_analytics_rpc_analysis_proto_rawDesc), len(file_services_analytics_rpc_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_analytics_rpc_analysis_proto_goTypes,
		DependencyIndexes: file_services_analytics_rpc_analysis_proto_depIdxs,
		MessageInfos:      file_services_analytics_rpc_analysis_proto_msgTypes,
	}.Build()
	File_services_analytics_rpc_analysis_proto = out.File
	file_services_analytics_rpc_analysis_proto_goTypes = nil
	file_services_analytics_rpc_analysis_proto_depIdxs = nil
}
