// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: analysis.proto

package analysisservice

import (
	"context"

	"url-shortner/services/analytics-rpc/analytics"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyticsRequest  = analytics.AnalyticsRequest
	AnalyticsResponse = analytics.AnalyticsResponse

	AnalysisService interface {
		GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
		CreateAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
		UpdateAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
		DeleteAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
	}

	defaultAnalysisService struct {
		cli zrpc.Client
	}
)

func NewAnalysisService(cli zrpc.Client) AnalysisService {
	return &defaultAnalysisService{
		cli: cli,
	}
}

func (m *defaultAnalysisService) GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	client := analytics.NewAnalysisServiceClient(m.cli.Conn())
	return client.GetAnalytics(ctx, in, opts...)
}

func (m *defaultAnalysisService) CreateAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	client := analytics.NewAnalysisServiceClient(m.cli.Conn())
	return client.CreateAnalytics(ctx, in, opts...)
}

func (m *defaultAnalysisService) UpdateAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	client := analytics.NewAnalysisServiceClient(m.cli.Conn())
	return client.UpdateAnalytics(ctx, in, opts...)
}

func (m *defaultAnalysisService) DeleteAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	client := analytics.NewAnalysisServiceClient(m.cli.Conn())
	return client.DeleteAnalytics(ctx, in, opts...)
}
